<?php 
return [
 'config_meta_tag_keywords' => 'Satocommerce,ecommerce'  ,
 'config_fb_url' => 'https://www.facebook.com/'  ,
 'config_linkedin_url' => 'https://www.linkedin.com/'  ,
 'config_twitter_url' => 'https://twitter.com/login?lang=en'  ,
 'config_youtube_url' => 'https://www.youtube.com/channel/UCiWzLziMAOk-oB0pig8TkEg/'  ,
 'config_mail_engine' => 'smtp'  ,
 'config_insta_url' => 'https://www.instagram.com/'  ,
 'config_smtp_username' => 'otrixapp@gmail.in'  ,
 'config_smtp_hostname' => 'smtp.googlemail.ddd'  ,
 'config_smtp_password' => 'abcdabcdefgefg'  ,
 'config_smtp_timeout' => '25'  ,
 'config_smtp_port' => '25'  ,
 'config_store_image' => '1691815628logootrix.png'  ,
 'config_alert_mail' => 'Register,Orders'  ,
 'config_icon_image' => '1729611045favicon.png'  ,
 'config_currency' => '$'  ,
 'config_fax' => '380001'  ,
 'config_telephone' => '+84 298 333 333'  ,
 'config_email' => 'sato@satoshop.com'  ,
 'config_geocode' => '54654'  ,
 'config_store_owner' => 'satoshi'  ,
 'config_address' => '35, Han Thuyen Street, Ward 6, Thu Duc, Ho Chi Minh City'  ,
 'config_store_name' => 'Satoshop'  ,
 'config_meta_tag_description' => 'SatoCommerce is your go-to destination for all your online shopping needs. Our ecommerce website offers an extensive collection of high-quality products at competitive prices, ranging from fashion and beauty to electronics and home essentials.
        Our user-friendly interface and fast-loading pages provide a seamless shopping experience for customers. We have optimized our website for search engines to ensure that our products are easily discoverable by potential customers.
        We prioritize customer satisfaction and have a dedicated customer support team available to assist you with any inquiries or concerns. With a secure payment gateway and fast shipping, we strive to make online shopping stress-free and convenient.
        At SatoCommerce, we are committed to providing you with the best online shopping experience possible. Browse our extensive collection today and discover something new!'  ,
 'config_meta_title' => 'Satocommerce Website'  ,
 'config_web_bg' => '#626ABB'  ,
 'config_currency' => '$'  ,
 'config_fax' => '380001'  ,
 'config_telephone' => '+84 298 333 333'  ,
 'config_email' => 'sato@satoshop.com'  ,
 'config_geocode' => '54654'  ,
 'config_address' => '35, Han Thuyen Street, Ward 6, Thu Duc, Ho Chi Minh City'  ,
 'config_store_owner' => 'satoshi'  ,
 'config_store_name' => 'Satoshop'  ,
 'config_encryption' => 'tls'  ,
 'config_from' => 'otrix@mail.in'  ,
 'config_from_name' => 'dasd'  ,
 'config_signup_discount_status' => '1'  ,
 'config_signup_discount' => '15'  ,
  "config_signup_discount_text" =>  "{\"4\":\"Sign Up  And  _DISCOUNT_  special discount on your first order\",\"15\":\"\\u0110\\u0103ng k\\u00fd  v\\u00e0 nh\\u1eadn _DISCOUNT_  chi\\u1ebft kh\\u1ea5u cho \\u0111\\u01a1n h\\u00e0ng \\u0111\\u1ea7u ti\\u00ean\"}",  'config_layout' => 'otrixlayout'  ,
 'config_twilio_sid' => 'AC03edc552fb'  ,
 'config_twilio_token' => '721bd6d11442ced'  ,
 'config_twilio_from' => '+17622'  ,
 'config_alert_sms' => 'Register,Orders'  ,
 'config_registerSMSContent' => 'Thank you for register on otrixcommerce'  ,
 'config_talk_to_expert' => '{\"4\":\"Hello\",\"15\":\"Xin ch\\u00e0o\"}'  ,
  "config_talk_to_expert" =>  "{\"4\":\"Hello\",\"15\":\"Xin ch\\u00e0o\"}",  'config_talk_to_expert_mobile' => '+84 298 333 333'  ,
 'config_social_status' => '1'  ,
 'config_accept_terms_before_order' => '1'  ,
];
